### ISSUE TITLE
Having mozblocklist create a new bug does not mark it as private

### ISSUE THREAD

**Issue by wagnerand** [kewisch/mozblocklist#1]
Having mozblocklist create a new bug does not mark it as private. We should set the right security group `blocklist-requests`.

**Comment by kewisch** [comment]
This looks like a Bugzilla API bug. It says:

> If you don't specify [the groups argument], then the bug will be added into all the groups that are set as being "Default" for this product.

I'm not specifying that argument. Now it does say the default for the **product**, and this is a per-component default. Possibly that wasn't taken into account.

**Comment by kewisch** [comment]
Related, I do have code in there right now that removes the group by default when pushing the block, but it seems that never worked. This sounds like an API bug to me as well.
