### ISSUE TITLE
Inconsistent use of "yN" / "yn"

### ISSUE THREAD

**Issue by jvillalobos** [kewisch/mozblocklist#21]
Typical block signing output:

> Ready to sign? [yn] y
> y
> Remove blocklist-requests security group? [yN] y
> y

Looking at the source, some prompts capitalize the `N` while others don't. I don't know what the best practice is, but the inconsistency is slowly killing me 🙃

**Comment by wagnerand** [comment]
That is on purpose. The uppercase letter indicates the default answer if you just press Enter.

So, for the first question, there is no default, which forces you to give an explicit answer/confirm you are ready. The second question has a default of N(o). If you just press Enter, the program will continue and the group won't be removed, to err on the side of caution.

**Comment by jvillalobos** [comment]
Okay, that explains it.
